scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47273/map.bin ~/Downloads/caustic_maps/47273.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47274/map.bin ~/Downloads/caustic_maps/47274.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47275/map.bin ~/Downloads/caustic_maps/47275.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47276/map.bin ~/Downloads/caustic_maps/47276.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47277/map.bin ~/Downloads/caustic_maps/47277.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47278/map.bin ~/Downloads/caustic_maps/47278.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47279/map.bin ~/Downloads/caustic_maps/47279.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47450/map.bin ~/Downloads/caustic_maps/47450.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47451/map.bin ~/Downloads/caustic_maps/47451.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47452/map.bin ~/Downloads/caustic_maps/47452.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47453/map.bin ~/Downloads/caustic_maps/47453.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47454/map.bin ~/Downloads/caustic_maps/47454.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47455/map.bin ~/Downloads/caustic_maps/47455.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47456/map.bin ~/Downloads/caustic_maps/47456.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47457/map.bin ~/Downloads/caustic_maps/47457.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47458/map.bin ~/Downloads/caustic_maps/47458.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47459/map.bin ~/Downloads/caustic_maps/47459.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/48770/map.bin ~/Downloads/caustic_maps/48770.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/48771/map.bin ~/Downloads/caustic_maps/48771.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/48772/map.bin ~/Downloads/caustic_maps/48772.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/48773/map.bin ~/Downloads/caustic_maps/48773.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/48774/map.bin ~/Downloads/caustic_maps/48774.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/48775/map.bin ~/Downloads/caustic_maps/48775.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/48776/map.bin ~/Downloads/caustic_maps/48776.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/48777/map.bin ~/Downloads/caustic_maps/48777.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/48778/map.bin ~/Downloads/caustic_maps/48778.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/48779/map.bin ~/Downloads/caustic_maps/48779.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/48780/map.bin ~/Downloads/caustic_maps/48780.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/48781/map.bin ~/Downloads/caustic_maps/48781.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/48782/map.bin ~/Downloads/caustic_maps/48782.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/48783/map.bin ~/Downloads/caustic_maps/48783.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/48784/map.bin ~/Downloads/caustic_maps/48784.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/48785/map.bin ~/Downloads/caustic_maps/48785.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/48786/map.bin ~/Downloads/caustic_maps/48786.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/48787/map.bin ~/Downloads/caustic_maps/48787.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/48788/map.bin ~/Downloads/caustic_maps/48788.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/48789/map.bin ~/Downloads/caustic_maps/48789.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/48790/map.bin ~/Downloads/caustic_maps/48790.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/48791/map.bin ~/Downloads/caustic_maps/48791.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/48792/map.bin ~/Downloads/caustic_maps/48792.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/48793/map.bin ~/Downloads/caustic_maps/48793.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/48794/map.bin ~/Downloads/caustic_maps/48794.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/48795/map.bin ~/Downloads/caustic_maps/48795.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/48796/map.bin ~/Downloads/caustic_maps/48796.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/48797/map.bin ~/Downloads/caustic_maps/48797.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/48798/map.bin ~/Downloads/caustic_maps/48798.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/48799/map.bin ~/Downloads/caustic_maps/48799.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49510/map.bin ~/Downloads/caustic_maps/49510.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49511/map.bin ~/Downloads/caustic_maps/49511.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49512/map.bin ~/Downloads/caustic_maps/49512.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49526/map.bin ~/Downloads/caustic_maps/49526.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49527/map.bin ~/Downloads/caustic_maps/49527.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49528/map.bin ~/Downloads/caustic_maps/49528.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49529/map.bin ~/Downloads/caustic_maps/49529.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49530/map.bin ~/Downloads/caustic_maps/49530.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49531/map.bin ~/Downloads/caustic_maps/49531.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49532/map.bin ~/Downloads/caustic_maps/49532.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49533/map.bin ~/Downloads/caustic_maps/49533.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49560/map.bin ~/Downloads/caustic_maps/49560.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49561/map.bin ~/Downloads/caustic_maps/49561.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49562/map.bin ~/Downloads/caustic_maps/49562.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49563/map.bin ~/Downloads/caustic_maps/49563.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49576/map.bin ~/Downloads/caustic_maps/49576.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49577/map.bin ~/Downloads/caustic_maps/49577.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49578/map.bin ~/Downloads/caustic_maps/49578.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49579/map.bin ~/Downloads/caustic_maps/49579.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49580/map.bin ~/Downloads/caustic_maps/49580.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49581/map.bin ~/Downloads/caustic_maps/49581.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49582/map.bin ~/Downloads/caustic_maps/49582.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49583/map.bin ~/Downloads/caustic_maps/49583.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49584/map.bin ~/Downloads/caustic_maps/49584.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49585/map.bin ~/Downloads/caustic_maps/49585.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49610/map.bin ~/Downloads/caustic_maps/49610.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49611/map.bin ~/Downloads/caustic_maps/49611.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49612/map.bin ~/Downloads/caustic_maps/49612.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49613/map.bin ~/Downloads/caustic_maps/49613.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49614/map.bin ~/Downloads/caustic_maps/49614.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49627/map.bin ~/Downloads/caustic_maps/49627.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49628/map.bin ~/Downloads/caustic_maps/49628.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49629/map.bin ~/Downloads/caustic_maps/49629.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49630/map.bin ~/Downloads/caustic_maps/49630.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49631/map.bin ~/Downloads/caustic_maps/49631.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49632/map.bin ~/Downloads/caustic_maps/49632.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49633/map.bin ~/Downloads/caustic_maps/49633.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49634/map.bin ~/Downloads/caustic_maps/49634.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49635/map.bin ~/Downloads/caustic_maps/49635.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49636/map.bin ~/Downloads/caustic_maps/49636.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49637/map.bin ~/Downloads/caustic_maps/49637.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49660/map.bin ~/Downloads/caustic_maps/49660.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49661/map.bin ~/Downloads/caustic_maps/49661.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49662/map.bin ~/Downloads/caustic_maps/49662.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49663/map.bin ~/Downloads/caustic_maps/49663.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49664/map.bin ~/Downloads/caustic_maps/49664.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49665/map.bin ~/Downloads/caustic_maps/49665.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49679/map.bin ~/Downloads/caustic_maps/49679.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49680/map.bin ~/Downloads/caustic_maps/49680.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49681/map.bin ~/Downloads/caustic_maps/49681.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49682/map.bin ~/Downloads/caustic_maps/49682.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49683/map.bin ~/Downloads/caustic_maps/49683.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/49684/map.bin ~/Downloads/caustic_maps/49684.bin