scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46352/map.bin ~/Downloads/caustic_maps/new/46352.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46353/map.bin ~/Downloads/caustic_maps/new/46353.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46354/map.bin ~/Downloads/caustic_maps/new/46354.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46355/map.bin ~/Downloads/caustic_maps/new/46355.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46356/map.bin ~/Downloads/caustic_maps/new/46356.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46357/map.bin ~/Downloads/caustic_maps/new/46357.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46358/map.bin ~/Downloads/caustic_maps/new/46358.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46359/map.bin ~/Downloads/caustic_maps/new/46359.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46360/map.bin ~/Downloads/caustic_maps/new/46360.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46361/map.bin ~/Downloads/caustic_maps/new/46361.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46362/map.bin ~/Downloads/caustic_maps/new/46362.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46363/map.bin ~/Downloads/caustic_maps/new/46363.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46364/map.bin ~/Downloads/caustic_maps/new/46364.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46365/map.bin ~/Downloads/caustic_maps/new/46365.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46366/map.bin ~/Downloads/caustic_maps/new/46366.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46367/map.bin ~/Downloads/caustic_maps/new/46367.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46368/map.bin ~/Downloads/caustic_maps/new/46368.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46369/map.bin ~/Downloads/caustic_maps/new/46369.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46370/map.bin ~/Downloads/caustic_maps/new/46370.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46371/map.bin ~/Downloads/caustic_maps/new/46371.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46372/map.bin ~/Downloads/caustic_maps/new/46372.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46373/map.bin ~/Downloads/caustic_maps/new/46373.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46374/map.bin ~/Downloads/caustic_maps/new/46374.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46375/map.bin ~/Downloads/caustic_maps/new/46375.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46376/map.bin ~/Downloads/caustic_maps/new/46376.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46377/map.bin ~/Downloads/caustic_maps/new/46377.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46378/map.bin ~/Downloads/caustic_maps/new/46378.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46379/map.bin ~/Downloads/caustic_maps/new/46379.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46380/map.bin ~/Downloads/caustic_maps/new/46380.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46381/map.bin ~/Downloads/caustic_maps/new/46381.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46382/map.bin ~/Downloads/caustic_maps/new/46382.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46383/map.bin ~/Downloads/caustic_maps/new/46383.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46384/map.bin ~/Downloads/caustic_maps/new/46384.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46385/map.bin ~/Downloads/caustic_maps/new/46385.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46386/map.bin ~/Downloads/caustic_maps/new/46386.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46387/map.bin ~/Downloads/caustic_maps/new/46387.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46388/map.bin ~/Downloads/caustic_maps/new/46388.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46389/map.bin ~/Downloads/caustic_maps/new/46389.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46410/map.bin ~/Downloads/caustic_maps/new/46410.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46411/map.bin ~/Downloads/caustic_maps/new/46411.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46412/map.bin ~/Downloads/caustic_maps/new/46412.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46413/map.bin ~/Downloads/caustic_maps/new/46413.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46414/map.bin ~/Downloads/caustic_maps/new/46414.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46415/map.bin ~/Downloads/caustic_maps/new/46415.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46416/map.bin ~/Downloads/caustic_maps/new/46416.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46417/map.bin ~/Downloads/caustic_maps/new/46417.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46418/map.bin ~/Downloads/caustic_maps/new/46418.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46419/map.bin ~/Downloads/caustic_maps/new/46419.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46420/map.bin ~/Downloads/caustic_maps/new/46420.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46421/map.bin ~/Downloads/caustic_maps/new/46421.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46422/map.bin ~/Downloads/caustic_maps/new/46422.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46423/map.bin ~/Downloads/caustic_maps/new/46423.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46424/map.bin ~/Downloads/caustic_maps/new/46424.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46425/map.bin ~/Downloads/caustic_maps/new/46425.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46426/map.bin ~/Downloads/caustic_maps/new/46426.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46427/map.bin ~/Downloads/caustic_maps/new/46427.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46428/map.bin ~/Downloads/caustic_maps/new/46428.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46429/map.bin ~/Downloads/caustic_maps/new/46429.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46430/map.bin ~/Downloads/caustic_maps/new/46430.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46431/map.bin ~/Downloads/caustic_maps/new/46431.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46432/map.bin ~/Downloads/caustic_maps/new/46432.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46433/map.bin ~/Downloads/caustic_maps/new/46433.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46434/map.bin ~/Downloads/caustic_maps/new/46434.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46435/map.bin ~/Downloads/caustic_maps/new/46435.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46436/map.bin ~/Downloads/caustic_maps/new/46436.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46437/map.bin ~/Downloads/caustic_maps/new/46437.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46438/map.bin ~/Downloads/caustic_maps/new/46438.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46439/map.bin ~/Downloads/caustic_maps/new/46439.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46440/map.bin ~/Downloads/caustic_maps/new/46440.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46441/map.bin ~/Downloads/caustic_maps/new/46441.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46442/map.bin ~/Downloads/caustic_maps/new/46442.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46443/map.bin ~/Downloads/caustic_maps/new/46443.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46444/map.bin ~/Downloads/caustic_maps/new/46444.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46445/map.bin ~/Downloads/caustic_maps/new/46445.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46446/map.bin ~/Downloads/caustic_maps/new/46446.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46447/map.bin ~/Downloads/caustic_maps/new/46447.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46448/map.bin ~/Downloads/caustic_maps/new/46448.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46449/map.bin ~/Downloads/caustic_maps/new/46449.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46450/map.bin ~/Downloads/caustic_maps/new/46450.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46451/map.bin ~/Downloads/caustic_maps/new/46451.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46452/map.bin ~/Downloads/caustic_maps/new/46452.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46453/map.bin ~/Downloads/caustic_maps/new/46453.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46454/map.bin ~/Downloads/caustic_maps/new/46454.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46455/map.bin ~/Downloads/caustic_maps/new/46455.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46456/map.bin ~/Downloads/caustic_maps/new/46456.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46457/map.bin ~/Downloads/caustic_maps/new/46457.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46458/map.bin ~/Downloads/caustic_maps/new/46458.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46459/map.bin ~/Downloads/caustic_maps/new/46459.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46480/map.bin ~/Downloads/caustic_maps/new/46480.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46481/map.bin ~/Downloads/caustic_maps/new/46481.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46482/map.bin ~/Downloads/caustic_maps/new/46482.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46483/map.bin ~/Downloads/caustic_maps/new/46483.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46484/map.bin ~/Downloads/caustic_maps/new/46484.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46485/map.bin ~/Downloads/caustic_maps/new/46485.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46486/map.bin ~/Downloads/caustic_maps/new/46486.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46487/map.bin ~/Downloads/caustic_maps/new/46487.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46488/map.bin ~/Downloads/caustic_maps/new/46488.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46489/map.bin ~/Downloads/caustic_maps/new/46489.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46490/map.bin ~/Downloads/caustic_maps/new/46490.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46491/map.bin ~/Downloads/caustic_maps/new/46491.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46492/map.bin ~/Downloads/caustic_maps/new/46492.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46493/map.bin ~/Downloads/caustic_maps/new/46493.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46494/map.bin ~/Downloads/caustic_maps/new/46494.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46495/map.bin ~/Downloads/caustic_maps/new/46495.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46496/map.bin ~/Downloads/caustic_maps/new/46496.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46497/map.bin ~/Downloads/caustic_maps/new/46497.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46498/map.bin ~/Downloads/caustic_maps/new/46498.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46499/map.bin ~/Downloads/caustic_maps/new/46499.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46500/map.bin ~/Downloads/caustic_maps/new/46500.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46501/map.bin ~/Downloads/caustic_maps/new/46501.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46502/map.bin ~/Downloads/caustic_maps/new/46502.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46503/map.bin ~/Downloads/caustic_maps/new/46503.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46504/map.bin ~/Downloads/caustic_maps/new/46504.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46505/map.bin ~/Downloads/caustic_maps/new/46505.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46506/map.bin ~/Downloads/caustic_maps/new/46506.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46507/map.bin ~/Downloads/caustic_maps/new/46507.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46508/map.bin ~/Downloads/caustic_maps/new/46508.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46509/map.bin ~/Downloads/caustic_maps/new/46509.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46510/map.bin ~/Downloads/caustic_maps/new/46510.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46511/map.bin ~/Downloads/caustic_maps/new/46511.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46512/map.bin ~/Downloads/caustic_maps/new/46512.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46513/map.bin ~/Downloads/caustic_maps/new/46513.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46514/map.bin ~/Downloads/caustic_maps/new/46514.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46515/map.bin ~/Downloads/caustic_maps/new/46515.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46516/map.bin ~/Downloads/caustic_maps/new/46516.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46517/map.bin ~/Downloads/caustic_maps/new/46517.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46518/map.bin ~/Downloads/caustic_maps/new/46518.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46519/map.bin ~/Downloads/caustic_maps/new/46519.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46520/map.bin ~/Downloads/caustic_maps/new/46520.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46521/map.bin ~/Downloads/caustic_maps/new/46521.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46522/map.bin ~/Downloads/caustic_maps/new/46522.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46523/map.bin ~/Downloads/caustic_maps/new/46523.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46524/map.bin ~/Downloads/caustic_maps/new/46524.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46525/map.bin ~/Downloads/caustic_maps/new/46525.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46526/map.bin ~/Downloads/caustic_maps/new/46526.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46527/map.bin ~/Downloads/caustic_maps/new/46527.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46528/map.bin ~/Downloads/caustic_maps/new/46528.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46529/map.bin ~/Downloads/caustic_maps/new/46529.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46530/map.bin ~/Downloads/caustic_maps/new/46530.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46531/map.bin ~/Downloads/caustic_maps/new/46531.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46532/map.bin ~/Downloads/caustic_maps/new/46532.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46533/map.bin ~/Downloads/caustic_maps/new/46533.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46534/map.bin ~/Downloads/caustic_maps/new/46534.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46535/map.bin ~/Downloads/caustic_maps/new/46535.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46536/map.bin ~/Downloads/caustic_maps/new/46536.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46537/map.bin ~/Downloads/caustic_maps/new/46537.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46538/map.bin ~/Downloads/caustic_maps/new/46538.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46539/map.bin ~/Downloads/caustic_maps/new/46539.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46540/map.bin ~/Downloads/caustic_maps/new/46540.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46541/map.bin ~/Downloads/caustic_maps/new/46541.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46542/map.bin ~/Downloads/caustic_maps/new/46542.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46543/map.bin ~/Downloads/caustic_maps/new/46543.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46544/map.bin ~/Downloads/caustic_maps/new/46544.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46545/map.bin ~/Downloads/caustic_maps/new/46545.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46546/map.bin ~/Downloads/caustic_maps/new/46546.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46547/map.bin ~/Downloads/caustic_maps/new/46547.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46548/map.bin ~/Downloads/caustic_maps/new/46548.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46549/map.bin ~/Downloads/caustic_maps/new/46549.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46550/map.bin ~/Downloads/caustic_maps/new/46550.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46551/map.bin ~/Downloads/caustic_maps/new/46551.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46552/map.bin ~/Downloads/caustic_maps/new/46552.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46553/map.bin ~/Downloads/caustic_maps/new/46553.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46554/map.bin ~/Downloads/caustic_maps/new/46554.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46555/map.bin ~/Downloads/caustic_maps/new/46555.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46556/map.bin ~/Downloads/caustic_maps/new/46556.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46557/map.bin ~/Downloads/caustic_maps/new/46557.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46558/map.bin ~/Downloads/caustic_maps/new/46558.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46559/map.bin ~/Downloads/caustic_maps/new/46559.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46560/map.bin ~/Downloads/caustic_maps/new/46560.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46561/map.bin ~/Downloads/caustic_maps/new/46561.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46562/map.bin ~/Downloads/caustic_maps/new/46562.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46563/map.bin ~/Downloads/caustic_maps/new/46563.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46564/map.bin ~/Downloads/caustic_maps/new/46564.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46565/map.bin ~/Downloads/caustic_maps/new/46565.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46566/map.bin ~/Downloads/caustic_maps/new/46566.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46567/map.bin ~/Downloads/caustic_maps/new/46567.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46568/map.bin ~/Downloads/caustic_maps/new/46568.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46569/map.bin ~/Downloads/caustic_maps/new/46569.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46580/map.bin ~/Downloads/caustic_maps/new/46580.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46581/map.bin ~/Downloads/caustic_maps/new/46581.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46582/map.bin ~/Downloads/caustic_maps/new/46582.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46583/map.bin ~/Downloads/caustic_maps/new/46583.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46584/map.bin ~/Downloads/caustic_maps/new/46584.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46585/map.bin ~/Downloads/caustic_maps/new/46585.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46586/map.bin ~/Downloads/caustic_maps/new/46586.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46587/map.bin ~/Downloads/caustic_maps/new/46587.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46588/map.bin ~/Downloads/caustic_maps/new/46588.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46589/map.bin ~/Downloads/caustic_maps/new/46589.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46590/map.bin ~/Downloads/caustic_maps/new/46590.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46591/map.bin ~/Downloads/caustic_maps/new/46591.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46592/map.bin ~/Downloads/caustic_maps/new/46592.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46593/map.bin ~/Downloads/caustic_maps/new/46593.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46594/map.bin ~/Downloads/caustic_maps/new/46594.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46595/map.bin ~/Downloads/caustic_maps/new/46595.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46596/map.bin ~/Downloads/caustic_maps/new/46596.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46597/map.bin ~/Downloads/caustic_maps/new/46597.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46598/map.bin ~/Downloads/caustic_maps/new/46598.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46599/map.bin ~/Downloads/caustic_maps/new/46599.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46600/map.bin ~/Downloads/caustic_maps/new/46600.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46601/map.bin ~/Downloads/caustic_maps/new/46601.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46602/map.bin ~/Downloads/caustic_maps/new/46602.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46603/map.bin ~/Downloads/caustic_maps/new/46603.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46604/map.bin ~/Downloads/caustic_maps/new/46604.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46605/map.bin ~/Downloads/caustic_maps/new/46605.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46606/map.bin ~/Downloads/caustic_maps/new/46606.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46607/map.bin ~/Downloads/caustic_maps/new/46607.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46608/map.bin ~/Downloads/caustic_maps/new/46608.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46609/map.bin ~/Downloads/caustic_maps/new/46609.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46610/map.bin ~/Downloads/caustic_maps/new/46610.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46611/map.bin ~/Downloads/caustic_maps/new/46611.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46612/map.bin ~/Downloads/caustic_maps/new/46612.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46613/map.bin ~/Downloads/caustic_maps/new/46613.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46614/map.bin ~/Downloads/caustic_maps/new/46614.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46615/map.bin ~/Downloads/caustic_maps/new/46615.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46616/map.bin ~/Downloads/caustic_maps/new/46616.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46617/map.bin ~/Downloads/caustic_maps/new/46617.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46618/map.bin ~/Downloads/caustic_maps/new/46618.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46619/map.bin ~/Downloads/caustic_maps/new/46619.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46620/map.bin ~/Downloads/caustic_maps/new/46620.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46621/map.bin ~/Downloads/caustic_maps/new/46621.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46622/map.bin ~/Downloads/caustic_maps/new/46622.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46623/map.bin ~/Downloads/caustic_maps/new/46623.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46624/map.bin ~/Downloads/caustic_maps/new/46624.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46625/map.bin ~/Downloads/caustic_maps/new/46625.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46626/map.bin ~/Downloads/caustic_maps/new/46626.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46627/map.bin ~/Downloads/caustic_maps/new/46627.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46628/map.bin ~/Downloads/caustic_maps/new/46628.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46629/map.bin ~/Downloads/caustic_maps/new/46629.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46660/map.bin ~/Downloads/caustic_maps/new/46660.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46661/map.bin ~/Downloads/caustic_maps/new/46661.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46662/map.bin ~/Downloads/caustic_maps/new/46662.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46663/map.bin ~/Downloads/caustic_maps/new/46663.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46664/map.bin ~/Downloads/caustic_maps/new/46664.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46665/map.bin ~/Downloads/caustic_maps/new/46665.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46666/map.bin ~/Downloads/caustic_maps/new/46666.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46667/map.bin ~/Downloads/caustic_maps/new/46667.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46668/map.bin ~/Downloads/caustic_maps/new/46668.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46669/map.bin ~/Downloads/caustic_maps/new/46669.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46670/map.bin ~/Downloads/caustic_maps/new/46670.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46671/map.bin ~/Downloads/caustic_maps/new/46671.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46672/map.bin ~/Downloads/caustic_maps/new/46672.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46673/map.bin ~/Downloads/caustic_maps/new/46673.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46674/map.bin ~/Downloads/caustic_maps/new/46674.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46675/map.bin ~/Downloads/caustic_maps/new/46675.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46676/map.bin ~/Downloads/caustic_maps/new/46676.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46677/map.bin ~/Downloads/caustic_maps/new/46677.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46678/map.bin ~/Downloads/caustic_maps/new/46678.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46679/map.bin ~/Downloads/caustic_maps/new/46679.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46680/map.bin ~/Downloads/caustic_maps/new/46680.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46681/map.bin ~/Downloads/caustic_maps/new/46681.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46682/map.bin ~/Downloads/caustic_maps/new/46682.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46683/map.bin ~/Downloads/caustic_maps/new/46683.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46684/map.bin ~/Downloads/caustic_maps/new/46684.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46685/map.bin ~/Downloads/caustic_maps/new/46685.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46686/map.bin ~/Downloads/caustic_maps/new/46686.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46687/map.bin ~/Downloads/caustic_maps/new/46687.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46688/map.bin ~/Downloads/caustic_maps/new/46688.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46689/map.bin ~/Downloads/caustic_maps/new/46689.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46690/map.bin ~/Downloads/caustic_maps/new/46690.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46691/map.bin ~/Downloads/caustic_maps/new/46691.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46692/map.bin ~/Downloads/caustic_maps/new/46692.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46693/map.bin ~/Downloads/caustic_maps/new/46693.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46694/map.bin ~/Downloads/caustic_maps/new/46694.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46695/map.bin ~/Downloads/caustic_maps/new/46695.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46696/map.bin ~/Downloads/caustic_maps/new/46696.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46697/map.bin ~/Downloads/caustic_maps/new/46697.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46698/map.bin ~/Downloads/caustic_maps/new/46698.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46699/map.bin ~/Downloads/caustic_maps/new/46699.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46700/map.bin ~/Downloads/caustic_maps/new/46700.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46701/map.bin ~/Downloads/caustic_maps/new/46701.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46702/map.bin ~/Downloads/caustic_maps/new/46702.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46703/map.bin ~/Downloads/caustic_maps/new/46703.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46704/map.bin ~/Downloads/caustic_maps/new/46704.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46705/map.bin ~/Downloads/caustic_maps/new/46705.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46706/map.bin ~/Downloads/caustic_maps/new/46706.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46707/map.bin ~/Downloads/caustic_maps/new/46707.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46708/map.bin ~/Downloads/caustic_maps/new/46708.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46709/map.bin ~/Downloads/caustic_maps/new/46709.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46710/map.bin ~/Downloads/caustic_maps/new/46710.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46711/map.bin ~/Downloads/caustic_maps/new/46711.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46712/map.bin ~/Downloads/caustic_maps/new/46712.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46713/map.bin ~/Downloads/caustic_maps/new/46713.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46714/map.bin ~/Downloads/caustic_maps/new/46714.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46715/map.bin ~/Downloads/caustic_maps/new/46715.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46716/map.bin ~/Downloads/caustic_maps/new/46716.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46717/map.bin ~/Downloads/caustic_maps/new/46717.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46718/map.bin ~/Downloads/caustic_maps/new/46718.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46719/map.bin ~/Downloads/caustic_maps/new/46719.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46720/map.bin ~/Downloads/caustic_maps/new/46720.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46721/map.bin ~/Downloads/caustic_maps/new/46721.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46722/map.bin ~/Downloads/caustic_maps/new/46722.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46723/map.bin ~/Downloads/caustic_maps/new/46723.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46724/map.bin ~/Downloads/caustic_maps/new/46724.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46725/map.bin ~/Downloads/caustic_maps/new/46725.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46726/map.bin ~/Downloads/caustic_maps/new/46726.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46727/map.bin ~/Downloads/caustic_maps/new/46727.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46728/map.bin ~/Downloads/caustic_maps/new/46728.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46729/map.bin ~/Downloads/caustic_maps/new/46729.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46730/map.bin ~/Downloads/caustic_maps/new/46730.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46731/map.bin ~/Downloads/caustic_maps/new/46731.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46732/map.bin ~/Downloads/caustic_maps/new/46732.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46733/map.bin ~/Downloads/caustic_maps/new/46733.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46734/map.bin ~/Downloads/caustic_maps/new/46734.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46735/map.bin ~/Downloads/caustic_maps/new/46735.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46736/map.bin ~/Downloads/caustic_maps/new/46736.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46737/map.bin ~/Downloads/caustic_maps/new/46737.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46738/map.bin ~/Downloads/caustic_maps/new/46738.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46739/map.bin ~/Downloads/caustic_maps/new/46739.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46770/map.bin ~/Downloads/caustic_maps/new/46770.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46771/map.bin ~/Downloads/caustic_maps/new/46771.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46772/map.bin ~/Downloads/caustic_maps/new/46772.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46773/map.bin ~/Downloads/caustic_maps/new/46773.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46774/map.bin ~/Downloads/caustic_maps/new/46774.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46775/map.bin ~/Downloads/caustic_maps/new/46775.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46776/map.bin ~/Downloads/caustic_maps/new/46776.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46777/map.bin ~/Downloads/caustic_maps/new/46777.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46778/map.bin ~/Downloads/caustic_maps/new/46778.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46779/map.bin ~/Downloads/caustic_maps/new/46779.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46780/map.bin ~/Downloads/caustic_maps/new/46780.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46781/map.bin ~/Downloads/caustic_maps/new/46781.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46782/map.bin ~/Downloads/caustic_maps/new/46782.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46783/map.bin ~/Downloads/caustic_maps/new/46783.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46784/map.bin ~/Downloads/caustic_maps/new/46784.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46785/map.bin ~/Downloads/caustic_maps/new/46785.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46786/map.bin ~/Downloads/caustic_maps/new/46786.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46787/map.bin ~/Downloads/caustic_maps/new/46787.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46788/map.bin ~/Downloads/caustic_maps/new/46788.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46789/map.bin ~/Downloads/caustic_maps/new/46789.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46790/map.bin ~/Downloads/caustic_maps/new/46790.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46791/map.bin ~/Downloads/caustic_maps/new/46791.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46792/map.bin ~/Downloads/caustic_maps/new/46792.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46793/map.bin ~/Downloads/caustic_maps/new/46793.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46794/map.bin ~/Downloads/caustic_maps/new/46794.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46795/map.bin ~/Downloads/caustic_maps/new/46795.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46796/map.bin ~/Downloads/caustic_maps/new/46796.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46797/map.bin ~/Downloads/caustic_maps/new/46797.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46798/map.bin ~/Downloads/caustic_maps/new/46798.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46799/map.bin ~/Downloads/caustic_maps/new/46799.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46860/map.bin ~/Downloads/caustic_maps/new/46860.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46861/map.bin ~/Downloads/caustic_maps/new/46861.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46862/map.bin ~/Downloads/caustic_maps/new/46862.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46863/map.bin ~/Downloads/caustic_maps/new/46863.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46864/map.bin ~/Downloads/caustic_maps/new/46864.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46865/map.bin ~/Downloads/caustic_maps/new/46865.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46866/map.bin ~/Downloads/caustic_maps/new/46866.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46867/map.bin ~/Downloads/caustic_maps/new/46867.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46868/map.bin ~/Downloads/caustic_maps/new/46868.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46869/map.bin ~/Downloads/caustic_maps/new/46869.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46870/map.bin ~/Downloads/caustic_maps/new/46870.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46871/map.bin ~/Downloads/caustic_maps/new/46871.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46872/map.bin ~/Downloads/caustic_maps/new/46872.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46873/map.bin ~/Downloads/caustic_maps/new/46873.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46874/map.bin ~/Downloads/caustic_maps/new/46874.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46875/map.bin ~/Downloads/caustic_maps/new/46875.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46876/map.bin ~/Downloads/caustic_maps/new/46876.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46877/map.bin ~/Downloads/caustic_maps/new/46877.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46878/map.bin ~/Downloads/caustic_maps/new/46878.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46879/map.bin ~/Downloads/caustic_maps/new/46879.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46880/map.bin ~/Downloads/caustic_maps/new/46880.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46881/map.bin ~/Downloads/caustic_maps/new/46881.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46882/map.bin ~/Downloads/caustic_maps/new/46882.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46883/map.bin ~/Downloads/caustic_maps/new/46883.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46884/map.bin ~/Downloads/caustic_maps/new/46884.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46885/map.bin ~/Downloads/caustic_maps/new/46885.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46886/map.bin ~/Downloads/caustic_maps/new/46886.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46887/map.bin ~/Downloads/caustic_maps/new/46887.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46888/map.bin ~/Downloads/caustic_maps/new/46888.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46889/map.bin ~/Downloads/caustic_maps/new/46889.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46890/map.bin ~/Downloads/caustic_maps/new/46890.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46891/map.bin ~/Downloads/caustic_maps/new/46891.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46892/map.bin ~/Downloads/caustic_maps/new/46892.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46893/map.bin ~/Downloads/caustic_maps/new/46893.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46894/map.bin ~/Downloads/caustic_maps/new/46894.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46895/map.bin ~/Downloads/caustic_maps/new/46895.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46896/map.bin ~/Downloads/caustic_maps/new/46896.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46897/map.bin ~/Downloads/caustic_maps/new/46897.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46898/map.bin ~/Downloads/caustic_maps/new/46898.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46899/map.bin ~/Downloads/caustic_maps/new/46899.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46900/map.bin ~/Downloads/caustic_maps/new/46900.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46901/map.bin ~/Downloads/caustic_maps/new/46901.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46902/map.bin ~/Downloads/caustic_maps/new/46902.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46903/map.bin ~/Downloads/caustic_maps/new/46903.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46904/map.bin ~/Downloads/caustic_maps/new/46904.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46905/map.bin ~/Downloads/caustic_maps/new/46905.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46906/map.bin ~/Downloads/caustic_maps/new/46906.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46907/map.bin ~/Downloads/caustic_maps/new/46907.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46908/map.bin ~/Downloads/caustic_maps/new/46908.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46909/map.bin ~/Downloads/caustic_maps/new/46909.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46910/map.bin ~/Downloads/caustic_maps/new/46910.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46911/map.bin ~/Downloads/caustic_maps/new/46911.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46912/map.bin ~/Downloads/caustic_maps/new/46912.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46913/map.bin ~/Downloads/caustic_maps/new/46913.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46914/map.bin ~/Downloads/caustic_maps/new/46914.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46915/map.bin ~/Downloads/caustic_maps/new/46915.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46916/map.bin ~/Downloads/caustic_maps/new/46916.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46917/map.bin ~/Downloads/caustic_maps/new/46917.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46918/map.bin ~/Downloads/caustic_maps/new/46918.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46919/map.bin ~/Downloads/caustic_maps/new/46919.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46950/map.bin ~/Downloads/caustic_maps/new/46950.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46951/map.bin ~/Downloads/caustic_maps/new/46951.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46952/map.bin ~/Downloads/caustic_maps/new/46952.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46953/map.bin ~/Downloads/caustic_maps/new/46953.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46954/map.bin ~/Downloads/caustic_maps/new/46954.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46955/map.bin ~/Downloads/caustic_maps/new/46955.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46956/map.bin ~/Downloads/caustic_maps/new/46956.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46957/map.bin ~/Downloads/caustic_maps/new/46957.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46958/map.bin ~/Downloads/caustic_maps/new/46958.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46959/map.bin ~/Downloads/caustic_maps/new/46959.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46960/map.bin ~/Downloads/caustic_maps/new/46960.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46961/map.bin ~/Downloads/caustic_maps/new/46961.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46962/map.bin ~/Downloads/caustic_maps/new/46962.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46963/map.bin ~/Downloads/caustic_maps/new/46963.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46964/map.bin ~/Downloads/caustic_maps/new/46964.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46965/map.bin ~/Downloads/caustic_maps/new/46965.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46966/map.bin ~/Downloads/caustic_maps/new/46966.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46967/map.bin ~/Downloads/caustic_maps/new/46967.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46968/map.bin ~/Downloads/caustic_maps/new/46968.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46969/map.bin ~/Downloads/caustic_maps/new/46969.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46970/map.bin ~/Downloads/caustic_maps/new/46970.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46971/map.bin ~/Downloads/caustic_maps/new/46971.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46972/map.bin ~/Downloads/caustic_maps/new/46972.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46973/map.bin ~/Downloads/caustic_maps/new/46973.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46974/map.bin ~/Downloads/caustic_maps/new/46974.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46975/map.bin ~/Downloads/caustic_maps/new/46975.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46976/map.bin ~/Downloads/caustic_maps/new/46976.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46977/map.bin ~/Downloads/caustic_maps/new/46977.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46978/map.bin ~/Downloads/caustic_maps/new/46978.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/46979/map.bin ~/Downloads/caustic_maps/new/46979.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47050/map.bin ~/Downloads/caustic_maps/new/47050.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47051/map.bin ~/Downloads/caustic_maps/new/47051.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47052/map.bin ~/Downloads/caustic_maps/new/47052.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47053/map.bin ~/Downloads/caustic_maps/new/47053.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47054/map.bin ~/Downloads/caustic_maps/new/47054.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47055/map.bin ~/Downloads/caustic_maps/new/47055.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47056/map.bin ~/Downloads/caustic_maps/new/47056.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47057/map.bin ~/Downloads/caustic_maps/new/47057.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47058/map.bin ~/Downloads/caustic_maps/new/47058.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47059/map.bin ~/Downloads/caustic_maps/new/47059.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47060/map.bin ~/Downloads/caustic_maps/new/47060.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47061/map.bin ~/Downloads/caustic_maps/new/47061.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47062/map.bin ~/Downloads/caustic_maps/new/47062.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47063/map.bin ~/Downloads/caustic_maps/new/47063.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47064/map.bin ~/Downloads/caustic_maps/new/47064.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47065/map.bin ~/Downloads/caustic_maps/new/47065.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47066/map.bin ~/Downloads/caustic_maps/new/47066.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47067/map.bin ~/Downloads/caustic_maps/new/47067.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47068/map.bin ~/Downloads/caustic_maps/new/47068.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47069/map.bin ~/Downloads/caustic_maps/new/47069.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47070/map.bin ~/Downloads/caustic_maps/new/47070.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47071/map.bin ~/Downloads/caustic_maps/new/47071.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47072/map.bin ~/Downloads/caustic_maps/new/47072.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47073/map.bin ~/Downloads/caustic_maps/new/47073.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47074/map.bin ~/Downloads/caustic_maps/new/47074.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47075/map.bin ~/Downloads/caustic_maps/new/47075.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47076/map.bin ~/Downloads/caustic_maps/new/47076.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47077/map.bin ~/Downloads/caustic_maps/new/47077.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47078/map.bin ~/Downloads/caustic_maps/new/47078.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47079/map.bin ~/Downloads/caustic_maps/new/47079.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47080/map.bin ~/Downloads/caustic_maps/new/47080.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47081/map.bin ~/Downloads/caustic_maps/new/47081.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47082/map.bin ~/Downloads/caustic_maps/new/47082.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47083/map.bin ~/Downloads/caustic_maps/new/47083.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47084/map.bin ~/Downloads/caustic_maps/new/47084.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47085/map.bin ~/Downloads/caustic_maps/new/47085.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47086/map.bin ~/Downloads/caustic_maps/new/47086.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47087/map.bin ~/Downloads/caustic_maps/new/47087.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47088/map.bin ~/Downloads/caustic_maps/new/47088.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47089/map.bin ~/Downloads/caustic_maps/new/47089.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47090/map.bin ~/Downloads/caustic_maps/new/47090.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47091/map.bin ~/Downloads/caustic_maps/new/47091.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47092/map.bin ~/Downloads/caustic_maps/new/47092.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47093/map.bin ~/Downloads/caustic_maps/new/47093.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47094/map.bin ~/Downloads/caustic_maps/new/47094.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47095/map.bin ~/Downloads/caustic_maps/new/47095.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47096/map.bin ~/Downloads/caustic_maps/new/47096.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47097/map.bin ~/Downloads/caustic_maps/new/47097.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47098/map.bin ~/Downloads/caustic_maps/new/47098.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47099/map.bin ~/Downloads/caustic_maps/new/47099.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47150/map.bin ~/Downloads/caustic_maps/new/47150.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47151/map.bin ~/Downloads/caustic_maps/new/47151.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47152/map.bin ~/Downloads/caustic_maps/new/47152.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47153/map.bin ~/Downloads/caustic_maps/new/47153.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47154/map.bin ~/Downloads/caustic_maps/new/47154.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47155/map.bin ~/Downloads/caustic_maps/new/47155.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47156/map.bin ~/Downloads/caustic_maps/new/47156.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47157/map.bin ~/Downloads/caustic_maps/new/47157.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47158/map.bin ~/Downloads/caustic_maps/new/47158.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47159/map.bin ~/Downloads/caustic_maps/new/47159.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47260/map.bin ~/Downloads/caustic_maps/new/47260.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47261/map.bin ~/Downloads/caustic_maps/new/47261.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47262/map.bin ~/Downloads/caustic_maps/new/47262.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47263/map.bin ~/Downloads/caustic_maps/new/47263.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47264/map.bin ~/Downloads/caustic_maps/new/47264.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47265/map.bin ~/Downloads/caustic_maps/new/47265.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47266/map.bin ~/Downloads/caustic_maps/new/47266.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47267/map.bin ~/Downloads/caustic_maps/new/47267.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47268/map.bin ~/Downloads/caustic_maps/new/47268.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47269/map.bin ~/Downloads/caustic_maps/new/47269.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47270/map.bin ~/Downloads/caustic_maps/new/47270.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47271/map.bin ~/Downloads/caustic_maps/new/47271.bin
scp skhakpas@nt.swin.edu.au:./codes/../../../fred/oz108/GERLUMPH_project/DATABASES/gerlumph_db/47272/map.bin ~/Downloads/caustic_maps/new/47272.bin
