#!/bin/bash

#SBATCH --partition=skylake       # Partition (job queue)
#SBATCH --job-name=gpu_05-22-23-13          # Assign an short name to your job
#SBATCH --mem-per-cpu=80G
#SBATCH --cpus-per-task=1             # Cores per task (>1 if multithread tasks)
#SBATCH --time=10:00:00               # Total run time limit (HH:MM:SS)
#SBATCH --output=python_24-05-22-23-13-51.out    # STDOUT output file
#SBATCH --error=python_24-05-22-23-13-51.err     # STDERR output file (optional)
#SBATCH --export=ALL                  # Export you current env to the job env
#SBATCH --mail-type=END
#SBATCH --mail-user=somayeh.khakpash@gmail.com
#SBATCH --gres=gpu:0                  # Number of GPUs
cd /home/skhakpas/codes
source ~/.bash_profile
module load gcc/11.3.0
module load openmpi/4.1.4
module load python/3.10.4
module load numpy/1.22.3-scipy-bundle-2022.05
module load matplotlib/3.5.2 
module load pandas/1.4.2-scipy-bundle-2022.05
module load tensorflow/2.11.0-cuda-11.7.0
module load pytorch/1.12.1-cuda-11.7.0
module load tqdm/4.64.0
module load scipy/1.8.1-scipy-bundle-2022.05 
. ~/maps/bin/activate
python evaluation.py -date=24-05-22-23-13-51 -KS_metric_calc=True -output_directory=./../../../fred/oz108/skhakpas/results/24-03-24-03-00-19/ -list_IDs_directory=./../data/eval_1000_maps.txt
